//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPersonalAppWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFP
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Porcentaje { get; set; }
        public Nullable<System.DateTime> Periodo { get; set; }
        public string Retiro { get; set; }
        public string Voluntario { get; set; }
        public string Empresa { get; set; }
        public Nullable<int> EmpresaId { get; set; }
    }
}
