//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPersonalAppWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campos
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Lugar { get; set; }
        public string Empresa { get; set; }
        public string Coordenadas { get; set; }
        public string Encargado { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public string Asistente { get; set; }
        public string TelefonoAsistente { get; set; }
    }
}
