//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPersonalAppWeb
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Comentario
    {
        public int Id { get; set; }
        public string Trabajador { get; set; }
        public Nullable<int> TrabajadorId { get; set; }
        [DisplayName("Aplicación de programa")]
        public Nullable<int> AplicacionDeProgramaId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        [DisplayName("Comentario")]
        public string Comentario1 { get; set; }
        public string Empresa { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public Nullable<int> ControlInventarioId { get; set; }
        public Nullable<int> IngresoId { get; set; }
        public Nullable<int> SolicitudId { get; set; }
        public Nullable<int> SolicitudDeCompraId { get; set; }
    }
}
