//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPersonalAppWeb
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class HyD
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Moneda { get; set; }
        public string Monto { get; set; }
        [DisplayName("Período")]
        public Nullable<System.DateTime> Periodo { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> IdTrabajador { get; set; }
        public Nullable<bool> Fijo { get; set; }
    }
}
