//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPersonalAppWeb
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Ingreso
    {
        public int Id { get; set; }
        public string Productos { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        [DisplayName("Ubicación")]
        public string Ubicacion { get; set; }
        public string Proveedor { get; set; }
        [DisplayName("Proveedor rut")]
        public string ProveedorRut { get; set; }
        public Nullable<int> ProveedorId { get; set; }
        public string Trabajador { get; set; }
        public Nullable<int> TrabajadorId { get; set; }
        public string Empresa { get; set; }
        public Nullable<int> EmpresaId { get; set; }
    }
}
