//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPersonalAppWeb
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Producto
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Unidad { get; set; }
        public string Tipo { get; set; }
        [DisplayName("Stock mínimo")]
        public Nullable<int> StockMin { get; set; }
        [DisplayName("Descripción")]
        public string Descripcion { get; set; }
        public byte[] Foto { get; set; }
        public byte[] Miniatura { get; set; }
        public string Empresa { get; set; }
        public Nullable<int> EmpresaId { get; set; }
    }
}
