//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPersonalAppWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroTrabajador
    {
        public int Id { get; set; }
        public string Uid { get; set; }
        public System.DateTime Fecha { get; set; }
        public byte[] Foto { get; set; }
        public string Campo { get; set; }
        public string Empresa { get; set; }
        public Nullable<int> IdTrabajador { get; set; }
        public string NombreTrabajador { get; set; }
        public Nullable<bool> Enviado { get; set; }
    }
}
