//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPersonalAppWeb
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Trabajador
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        [DisplayName("Apellido paterno")]
        public string ApellidoPaterno { get; set; }
        [DisplayName("Apellido materno")]
        public string ApellidoMaterno { get; set; }
        public string Rut { get; set; }
        [DisplayName("Dirección")]
        public string Direccion { get; set; }
        public string Sexo { get; set; }
        [DisplayName("Teléfono")]
        public string Telefono { get; set; }
        public string Email { get; set; }
        [DisplayName("Número de pulsera")]
        public string Numero { get; set; }
        [DisplayName("Foto de carnet")]
        public byte[] FotoCarnet { get; set; }
        [DisplayName("Foto de perfil")]
        public byte[] Foto { get; set; }
        public string Uid { get; set; }
        public string Contratista { get; set; }
        public string Empresa { get; set; }
        public Nullable<bool> Habilitado { get; set; }
        public string Nomina { get; set; }
        public string Contrato { get; set; }
        public string Anexo { get; set; }
        public string Odi { get; set; }
        [DisplayName("Registro Epp")]
        public string Registro_Epp { get; set; }
        [DisplayName("Registro RIOHS")]
        public string Registro_RIOHS { get; set; }
        [DisplayName("Registro capacitación")]
        public string Registro_capacitación { get; set; }
        [DisplayName("Examen altura física")]
        public string Examen_altura_física { get; set; }
        [DisplayName("Procedimientos de trabajo")]
        public string Procedimientos_de_trabajo { get; set; }
        [DisplayName("Documento Covid 19")]
        public string Documento_Covid_19 { get; set; }
        public Nullable<System.DateTime> Expiración { get; set; }
    }
}
