//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPersonalAppWeb
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class AplicacionDePrograma
    {
        public int Id { get; set; }
        [DisplayName("Solicitud")]
        public Nullable<int> SolicitudId { get; set; }
        [DisplayName("Fecha de inicio")]
        public Nullable<System.DateTime> FechaInicio { get; set; }
        [DisplayName("Fecha de fin")]
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string Empresa { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        [DisplayName("Nombre")]
        public string Ubicacion { get; set; }
    }
}
