//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPersonalAppWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finiquito
    {
        public int Id { get; set; }
        public string Causa { get; set; }
        public string Texto { get; set; }
        public Nullable<System.DateTime> FechaDocumento { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<double> DiasDeVacaciones { get; set; }
        public Nullable<int> Dias { get; set; }
        public Nullable<int> SueldoMensual { get; set; }
        public Nullable<int> AvisoPrevio { get; set; }
        public Nullable<int> FactorAvisoPrevio { get; set; }
        public Nullable<int> Indemnización { get; set; }
        public Nullable<double> FactorIndemnizacion { get; set; }
        public Nullable<double> Vacaciones { get; set; }
        public Nullable<double> FactorVacaciones { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> IdTrabajador { get; set; }
    }
}
