//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPersonalAppWeb
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class HorasExtras
    {
        public int Id { get; set; }
        public Nullable<double> Horas { get; set; }
        public Nullable<int> Porcentaje { get; set; }
        [DisplayName("Período")]
        public Nullable<System.DateTime> Periodo { get; set; }
        public Nullable<int> IdTrabajador { get; set; }
    }
}
