//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPersonalAppWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licencia
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Desde { get; set; }
        public Nullable<int> Dias { get; set; }
        public Nullable<System.DateTime> Hasta { get; set; }
        public string Causa { get; set; }
        public Nullable<int> IdTrabajador { get; set; }
    }
}
