//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPersonalAppWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SgajcpEntities : DbContext
    {
        public SgajcpEntities()
            : base("name=SgajcpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Campos> Campos { get; set; }
        public virtual DbSet<Cuentas> Cuentas { get; set; }
        public virtual DbSet<RegistroTrabajador> RegistroTrabajador { get; set; }
        public virtual DbSet<Pulseras> Pulseras { get; set; }
        public virtual DbSet<Empresas> Empresas { get; set; }
        public virtual DbSet<Trabajador> Trabajador { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<Casino> Casino { get; set; }
        public virtual DbSet<Personas> Personas { get; set; }
    }
}
