//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPersonalAppWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificacion
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Correo { get; set; }
        public Nullable<int> SolicitudId { get; set; }
        public Nullable<int> SolicitudDeCompraId { get; set; }
        public string Estado { get; set; }
        public string Texto { get; set; }
        public Nullable<int> CuentaId { get; set; }
        public string Dato { get; set; }
        public string Info { get; set; }
    }
}
