//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPersonalAppWeb
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Personas
    {
        public int Id { get; set; }
        [DisplayName("Centro de costo 1")]
        public string CentroCosto1 { get; set; }
        [DisplayName("Centro de costo 2")]
        public string CentroCosto2 { get; set; }
        [DisplayName("Glosa centro de costo")]
        public string GlosaCosto { get; set; }
        [DisplayName("Ubicación")]
        public string Ubicacion { get; set; }
        [DisplayName("Instalación")]
        public string Instalacion { get; set; }
        public string Rut { get; set; }
        [DisplayName("Nombre completo")]
        public string Nombre { get; set; }
        [DisplayName("Glosa puesto")]
        public string GlosaPuesto { get; set; }
    }
}
