//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPersonalAppWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        public int Id { get; set; }
        public string Moneda { get; set; }
        public Nullable<int> Monto { get; set; }
        public Nullable<int> Meses { get; set; }
        public Nullable<double> Interes { get; set; }
        public Nullable<System.DateTime> Inicio { get; set; }
        public Nullable<int> IdTrabajador { get; set; }
        public string Empresa { get; set; }
        public Nullable<int> EmpresaId { get; set; }
    }
}
