//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPersonalAppWeb
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Stock
    {
        public int Id { get; set; }
        public string Producto { get; set; }
        public Nullable<int> ProductoId { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<int> SolicitudId { get; set; }
        public Nullable<int> SolicitudDeCompraId { get; set; }
        public Nullable<int> IngresoId { get; set; }
        public string Empresa { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public Nullable<int> UbicacionId { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> ControlId { get; set; }
        [DisplayName("Retirar bajo 0")]
        public Nullable<bool> RetirarBajo0 { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
