//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPersonalAppWeb
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Trabajador
    {
        public int Id { get; set; }
        [DisplayName ("Nombre")]
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Rut { get; set; }
        public string TipoCuenta { get; set; }
        public string Banco { get; set; }
        public string NumeroCuenta { get; set; }
        public string Contratado { get; set; }
        public string CodPersonal { get; set; }
        public string EstadoCivil { get; set; }
        public string Nacionalidad { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Direccion { get; set; }
        public string Sexo { get; set; }
        public string Ciudad { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string CargasFamiliares { get; set; }
        public string TrampoAsignacionFamiliar { get; set; }
        public Nullable<int> CargasSimples { get; set; }
        public Nullable<int> CargasMaternales { get; set; }
        public Nullable<int> CargasInvalidas { get; set; }
        public string RegimenPrevicional { get; set; }
        public string AsignacionFamiliar { get; set; }
        public string AsignacionFamiliarRetroactiva { get; set; }
        public string ReintegroCargasFamiliares { get; set; }
        public string SolicitudTrabajadorJoven { get; set; }
        public string AFP { get; set; }
        public string TipoLineaAFP { get; set; }
        public string RentaImponibleAFP { get; set; }
        public string CotizacionObligatoriaAFP { get; set; }
        public string SIS { get; set; }
        public string AhorroVoluntarioAFP { get; set; }
        public string RentaImpSustitutiva { get; set; }
        public string TasaPactadaSus { get; set; }
        public string AporteIndemSus { get; set; }
        public string NPeriodosSus { get; set; }
        public Nullable<System.DateTime> PeriodosDesdeSus { get; set; }
        public string PuestoTrabajoPesado { get; set; }
        public Nullable<System.DateTime> PerodoHastaSus { get; set; }
        public string PorcentajeTrabajoPesado { get; set; }
        public string MontoTrabajoPesado { get; set; }
        public string CodigoMovimientoDePersonal { get; set; }
        public Nullable<System.DateTime> InicioMovimientoPersonal { get; set; }
        public Nullable<System.DateTime> FinMovimientoPersonal { get; set; }
        public string TrampoAFP { get; set; }
        public string Jubiulado { get; set; }
        public string SeguroCesantia { get; set; }
        public string Mutual { get; set; }
        public string Salud { get; set; }
        public string NombreEmer { get; set; }
        public string VinculoEmer { get; set; }
        public string DireccionEmer { get; set; }
        public string TelefonoEmer { get; set; }
        public string Cargo { get; set; }
        public string NombreJefe { get; set; }
        public string Campo { get; set; }
        public string Empleador { get; set; }
        public string Contrato { get; set; }
        public string Jornada { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaTermino { get; set; }
        public Nullable<int> SueldoBase { get; set; }
        public Nullable<int> Gratificacion { get; set; }
        public Nullable<int> SueldoBruto { get; set; }
        public string TipoPago { get; set; }
        public Nullable<int> FactorHE { get; set; }
        public Nullable<int> Colacion { get; set; }
        public Nullable<int> Movilizacion { get; set; }
        public Nullable<int> DiasVacacionesAño { get; set; }
        public string JefeDirecto { get; set; }
        public string Gerente { get; set; }
        public byte[] FotoCarnet { get; set; }
        public byte[] Foto { get; set; }
        public string Uid { get; set; }
        public string Empresa { get; set; }
        public string APVI { get; set; }
        public string CodigoAPVI { get; set; }
        public string NumeroAPVI { get; set; }
        public string FormaPagoAPVI { get; set; }
        public string CotizacionAPVI { get; set; }
        public string CotizaciónDepositosConvenidos { get; set; }
        public string APVC { get; set; }
        public string CodigoAPVC { get; set; }
        public string NumeroAPVC { get; set; }
        public string FormaPagoAPVC { get; set; }
        public string CotizacionTrabajadorAPVC { get; set; }
        public string CotizacionEmpleadorAPVC { get; set; }
        public string AfiliadoVoluntario { get; set; }
        public string RutAV { get; set; }
        public string ApellidoPaternoAV { get; set; }
        public string ApellidoMaternoAV { get; set; }
        public string NombresAV { get; set; }
        public string CodigoMovimientoPersonalAV { get; set; }
        public Nullable<System.DateTime> DesdeAV { get; set; }
        public Nullable<System.DateTime> HastaAV { get; set; }
        public string AFPAV { get; set; }
        public string MontoCapitalizacionVoluntaria { get; set; }
        public string MontoAV { get; set; }
        public string PeriodosAV { get; set; }
        public string CodigoExcaja { get; set; }
        public string TasaExcaja { get; set; }
        public string RentaImponibleIPS { get; set; }
        public string CotizacionObligatoriaIPS { get; set; }
        public string RentaImponibleDesahucio { get; set; }
        public string CodigoExcajaDesahucio { get; set; }
        public string TasaCotizacionDesahucio { get; set; }
        public string CotizaciónDesahucio { get; set; }
        public string CotizacionFonasa { get; set; }
        public string CotizacionISL { get; set; }
        public string BonificacionLey { get; set; }
        public string DescuentoPorCargasFamiliaresISL { get; set; }
        public string BonosGobierno { get; set; }
        public string CodigoIntitucionSalud { get; set; }
        public string NumeroFun { get; set; }
        public string RentaImponibleIsapre { get; set; }
        public string MonedaDelPlanPactadoIsapre { get; set; }
        public string CotizacionPactada { get; set; }
        public string CotizacionIsapre { get; set; }
        public string CotizacionIsapreAV { get; set; }
        public string MontoGES { get; set; }
        public string CodigoCCAF { get; set; }
        public string RentaImponibleCCAF { get; set; }
        public string CreditosPersonalesCCAF { get; set; }
        public string DescuentoDentalCCAF { get; set; }
        public string DescuentosPorLeasing { get; set; }
        public string DescuentoPorSeguroDeVidaCCAF { get; set; }
        public string OtrosDescuentosCCAF { get; set; }
        public string CotizacionCCAFNoAfiniladosIsapres { get; set; }
        public string DescuentoCargasFamiliaresCCAF { get; set; }
        public string OtrosDescuentosCCAF1 { get; set; }
        public string OtrosDescuentosCCAF2 { get; set; }
        public string BonosGobiernoCCAF { get; set; }
        public string CodigoSucursalCCAF { get; set; }
        public string CodigoMutualidad { get; set; }
        public string RentaImponibleMutual { get; set; }
        public string CotizacionAccidenteMutual { get; set; }
        public string SucursalParaPagoMutual { get; set; }
        public string RentaImponibleSeguroCensantia { get; set; }
        public string AporteTrabajadorSeguroCensatia { get; set; }
        public string AporteEmpleadorSeguroCesantia { get; set; }
        public string Subsidio { get; set; }
        public string DatosEmpresa { get; set; }
    }
}
