//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPersonalAppWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacaciones
    {
        public int Id { get; set; }
        public string Año { get; set; }
        public Nullable<double> Normales { get; set; }
        public Nullable<double> Progresivas { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> TomadasNormales { get; set; }
        public Nullable<double> TomadasProgresivas { get; set; }
        public Nullable<double> Saldo { get; set; }
        public Nullable<int> IdTrabajador { get; set; }
    }
}
